// ══════════════════════════════════════════════════
//  STATE
// ══════════════════════════════════════════════════
const S = {
  // Import
  importedSheets: {},      // {sheetName: [{tag,desc,group,cat,id,priority}]}
  importedFile: null,

  // Project
  projectDone: false,

  // Equipment
  selectedEq: new Set(),   // "category|name"
  eqDone: false,

  // Configure
  quantities: {},          // "category|name" -> number
  // Alarm state per entity-instance: "E{n}" or "L{n}"
  // entityAlarms[entityKey] = [{...alarm, deleted:bool}]
  entityAlarms: {},
  activeEntity: null,
  showDeleted: false,

  // Settings
  settingsOpen: false,
  settingsSort: {field:'tag', dir:1},
  settingsPage: 1,
  settingsPageSize: 30,
  customAlarms: [],

  commonAlarms: [],   // generated by common alarms wizard
  customProjectAlarms: [], // project-specific custom alarms
  projectStatus: 'draft', // draft | inprogress | completed | delivered
  customEquipment: [], // added via Settings
  activeAlarmTypeFilter: '',  // alarm type name filter in configure view

  // Nav unlock
  unlocked: new Set(['project'])
};

// ══════════════════════════════════════════════════
//  EQUIPMENT CATEGORIES
// ══════════════════════════════════════════════════
const EQ_CATS = [
  {cat:"Packers",items:["Drop type Packer","2-Axis Delta Robot Packer","Pick & Place Gantry Packer","3-Axis Delta Robot Packer","Tray & Crate Packer (2 in 1)","Top Loading RSC Packer (3 in 1)"]},
  {cat:"Palletizers",items:["Semi Automatic Palletizer","Robotic Crate Palletizer","Pantograph Palletizer","Hybrid Palletizer","Robotic Palletizer"]},
  {cat:"Depalletizers",items:["Robotic Crate Depalletizer","Pantograph Depalletizer","Sweep Type Depalletizer","Robotic Depalletizer"]},
  {cat:"Inspection Systems",items:["Crate Inspection","Wooden Pallet Inspection","Plastic Pallet Inspection","Full Bottle Inspection","Empty Bottle Inspection"]},
  {cat:"Accumulation Systems",items:["Accumulation Turntable","FIFO Accumulation Table","Mass Flow Accumulation Table","Row Accumulation Table","Loop Accumulation"]},
  {cat:"Primary & Secondary Manipulation",items:["Continuous Turning Device","Starwheel Divider","Continuous Pusher","Segregation Unit For Cartons","Step Divider - Merge For Primary"]},
  {cat:"Empty Bottle Handling",items:["Debagger for square-oval Bottles","Invert Cleaner","Debagger for round bottles"]},
  {cat:"Crate Handling",items:["MDR Conveying","Motorized Crate Chute","Crate Merging Table","Crate Diverter","Crate Orientor","Side grip crate elevator - lowerator"]},
  {cat:"Pallet Handling",items:["Pallet Elevator - lowerator","Pallet turntable","Transfer Car","Pallet 90 Degrees Transfer Unit"]},
  {cat:"Plastic & Steel Rack Handling",items:["Robotic Rack Unloader","Rack Washer","Robotic Rack Loader"]},
  {cat:"Conveying Systems",items:["Modular Plastic Belt Conveyor","Belt Conveyor","Modular Chain Conveyors","Plastic Chain Conveyor for crate","Roller Conveyor","Roller - Chain Conveyor for Pallet","Roller Conveyor for Pallet","Modular Chain Conveyor for Pallet"]}
];

// Maps equipment name to Excel sheet name(s) to pull alarms from
const EQ_SHEET_MAP = {
  // exact equipment name -> sheet name in Excel
  "Drop type Packer":"Packers","2-Axis Delta Robot Packer":"Packers","Pick & Place Gantry Packer":"Packers",
  "3-Axis Delta Robot Packer":"Packers","Tray & Crate Packer (2 in 1)":"Packers","Top Loading RSC Packer (3 in 1)":"Packers",
  "Semi Automatic Palletizer":"Palletizer","Robotic Crate Palletizer":"Palletizer","Pantograph Palletizer":"Palletizer",
  "Hybrid Palletizer":"Palletizer","Robotic Palletizer":"Palletizer",
  "Robotic Crate Depalletizer":"Depalletizers","Pantograph Depalletizer":"Depalletizers",
  "Sweep Type Depalletizer":"Depalletizers","Robotic Depalletizer":"Depalletizers",
  "Crate Inspection":"Inspection Systems","Wooden Pallet Inspection":"Inspection Systems",
  "Plastic Pallet Inspection":"Inspection Systems","Full Bottle Inspection":"Inspection Systems","Empty Bottle Inspection":"Inspection Systems",
  "Accumulation Turntable":"Accumulation","FIFO Accumulation Table":"Accumulation",
  "Mass Flow Accumulation Table":"Accumulation","Row Accumulation Table":"Accumulation","Loop Accumulation":"Accumulation",
  "Continuous Turning Device":"Motor","Starwheel Divider":"Motor","Continuous Pusher":"Motor",
  "Segregation Unit For Cartons":"Motor","Step Divider - Merge For Primary":"Motor",
  "Debagger for square-oval Bottles":"Empty Bottle Handling","Invert Cleaner":"Empty Bottle Handling","Debagger for round bottles":"Empty Bottle Handling",
  "MDR Conveying":"MDR","Motorized Crate Chute":"Crate Handling","Crate Merging Table":"Crate Handling",
  "Crate Diverter":"Crate Handling","Crate Orientor":"Crate Handling","Side grip crate elevator - lowerator":"Crate Handling",
  "Pallet Elevator - lowerator":"Pallet Handling","Pallet turntable":"Pallet Handling","Transfer Car":"Pallet Handling","Pallet 90 Degrees Transfer Unit":"Pallet Handling",
  "Robotic Rack Unloader":"Plastic & Steel Rack Handling","Rack Washer":"Plastic & Steel Rack Handling","Robotic Rack Loader":"Plastic & Steel Rack Handling",
  "Modular Plastic Belt Conveyor":"Conveying Systems","Belt Conveyor":"Conveying Systems","Modular Chain Conveyors":"Conveying Systems",
  "Plastic Chain Conveyor for crate":"Conveying Systems","Roller Conveyor":"Conveying Systems",
  "Roller - Chain Conveyor for Pallet":"Conveying Systems","Roller Conveyor for Pallet":"Conveying Systems","Modular Chain Conveyor for Pallet":"Conveying Systems"
};


// ══════════════════════════════════════════════════
